author: pigigaldi
author_url: https://twitter.com/pigigaldi
copyright: © 2020 Pock, some rights reserved.
readme: README.md

documentation: docs/guides/*.md

module: PockKit
module_version: 0.1.4

output: docs/public
theme: apple

github_url: https://github.com/pigigaldi/PockKit
github_file_prefix: https://github.com/pigigaldi/PockKit/tree/master

clean: true
podspec: PockKit.podspec
